const assert = require('node:assert/strict');
const fs = require('node:fs');
const html = fs.readFileSync('dist/index.html','utf8');
assert.doesNotMatch(html,/data-hero-intro|has-hero-intro/, 'timed splash no longer blocks the scroll hero');
assert.equal((html.match(/<h1\b/g)||[]).length,1,'homepage has one primary heading');
assert.match(html,/<h1 id="cinematic-title">AVANTAGE AI<\/h1>/);
assert.match(html,/AI Agents · Automation · Software/);
assert.match(html,/data-cinematic-skip/,'cinematic can be skipped');
assert.match(html,/id="after-cinematic" tabindex="-1"/,'skip destination accepts keyboard focus');
assert.ok(html.indexOf('cinematic-brand') < html.indexOf('href="contact.html"',html.indexOf('cinematic-brand')));
console.log('cinematic intro accessibility contract verified');
